eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8889
spring:
  application:
    name: service-config
#feign:
#  hystrix:
#    enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15130125905/spring-cloud-config.git  #git仓库地址，就是刚才创建的git仓库
          skipSslValidation: true #跳过校验
          basedir: E:///config-center///config #从git仓库拉取到的文件在本地存储的位置，可自行修改或删掉，默认存储在C盘
        # bootstrap: true




